version: "3.9"  # optional since v1.27.0
services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - NEZHAAGENT=de2e65cb080ec0a2a4
  web1:
    build: .
    ports:
      - "80:80"
    environment:
      - NEZHAAGENT=e01a30665d64f7d44b
